# Generated by Django 5.1.2 on 2025-01-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
