# Generated by Django 5.1.2 on 2024-10-08 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('personality', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('eyes_and_fur', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=300)),
                ('health', models.CharField(max_length=300)),
                ('maintenance', models.CharField(max_length=300)),
                ('feeding', models.CharField(max_length=300)),
                ('picture', models.ImageField(upload_to='upload/cat/')),
                ('vitamin_sup', models.BooleanField(default=False)),
                ('mineral_sup', models.BooleanField(default=False)),
                ('omega_sup', models.BooleanField(default=False)),
                ('probiotic_sup', models.BooleanField(default=False)),
                ('amino_asid_sup', models.BooleanField(default=False)),
                ('herbal_sup', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pishi.category')),
            ],
        ),
    ]
