# Generated by Django 5.1.2 on 2024-10-08 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pishi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pishi.category'),
        ),
    ]
