# Generated by Django 5.1.2 on 2024-10-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pishi', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='upload/catcategory/'),
        ),
    ]
