# Generated by Django 5.1.2 on 2024-10-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pishi', '0004_category_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
