# Generated by Django 5.1.2 on 2024-10-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pishi', '0006_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
