# Generated by Django 5.1.2 on 2024-10-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pishi', '0008_remove_cat_amino_asid_sup_remove_cat_herbal_sup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='product_category',
            field=models.ManyToManyField(related_name='consuming_cats', to='pishi.category'),
        ),
    ]
