# Generated by Django 5.1.2 on 2024-10-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catshop', '0011_alter_order_date'),
        ('pishi', '0009_cat_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='product_category',
            field=models.ManyToManyField(related_name='consuming_cats', to='catshop.category'),
        ),
    ]
