# Generated by Django 5.1.2 on 2024-10-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catshop', '0012_alter_order_date'),
        ('pishi', '0010_alter_cat_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='product_category',
            field=models.ManyToManyField(to='catshop.category'),
        ),
    ]
