# Generated by Django 5.1.2 on 2024-10-30 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catshop', '0014_alter_order_date'),
        ('pishi', '0011_alter_cat_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Related_Products_For_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pishi.cat')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catshop.category')),
            ],
        ),
    ]
