# Generated by Django 5.1.2 on 2024-11-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pishi', '0012_related_products_for_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='product_category',
        ),
    ]
